version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/

hooks:
  BeforeInstall:
    - location: ./beforeInstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 300
      runas: ec2-user
