version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - mkdir /etc/yum.repos.d/
      - sudo curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
      - sudo apt-get install -y awscli
      - sudo apt-get install yarn -y
      - cd api
      - npm install dotenv
      - npm install --save-dev nodemon
      - npm install
      - cd ../client
      - npm install
  
  pre_build:
    commands:
      - echo "Obteniendo variables desde SSM y RDS..."

      # Leer variables desde Parameter Store
      - DB_USER=$(aws ssm get-parameter --name "DB_USER" --query "Parameter.Value" --output text)
      - DB_PASSWORD=$(aws ssm get-parameter --name "DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
      - DB_NAME="myapp"
      # Obtener el endpoint RDS por ID
      - DB_HOST=$(aws rds describe-db-instances --db-instance-identifier myrdsinstance --query "DBInstances[0].Endpoint.Address" --output text)

      # Crear el archivo .env en /api/
      - |
        echo "Creando archivo .env en /api/"
        cat <<EOF > ../api/.env
        DB_USER=$DB_USER
        DB_PASSWORD=$DB_PASSWORD
        DB_HOST=$DB_HOST
        DB_NAME=$DB_NAME
        EOF
  build:
    commands:
      - sudo yarn build
      - mv build ../build
artifacts:
  files:
    - 'build/**/*'               
    - 'api/**/*'                 
    - 'appspec.yml'              
    - 'beforeInstall.sh'         
    - 'afterInstall.sh'  