version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - mkdir /etc/yum.repos.d/
      - sudo curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
      - sudo apt-get install yarn -y
      - cd client
      - npm install
  build:
    commands:
      - sudo yarn build
artifacts:
  files:
    # - 'client/build'
    - **/*