version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing tools...
      - yum update -y
      - yum install -y git zip
      - npm install -g npm@11.3.0
      - npm install -g pm2
      - curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
      - yum install -y yarn
  pre_build:
    commands:
      - echo Cloning repository...
      - git clone https://github.com/alexhippo/full-stack-app-with-react-rest-api.git
  build:
    commands:
      - echo Building frontend...
      - cd full-stack-app-with-react-rest-api/client
      - npm install
      - yarn build
      - echo Preparing deployment artifact...
      - mkdir build-output
      - cp -r build build-output
  post_build:
    commands:
      - echo Zipping deployment package...
      - cd build-output
      - zip -r ../app-deploy.zip .
artifacts:
  files:
    - app-deploy.zip